### ISSUE TITLE
error: failed to run custom build command for `halo2curves v0.6.1`

### ISSUE THREAD

**Issue by Meyanis95** [avras/nova-sha256#5]
Hello, 

I was trying to run the repo on my machine but Rust wasn't able to build the project. 

Here is the error after running `cargo build --release`

```
error: failed to run custom build command for `halo2curves v0.6.1`

Caused by:
  process didn't exit successfully: `/Users/me/nova-sha256/target/release/build/halo2curves-70e57f3b431621b6/build-script-build` (exit status: 1)
  --- stderr
  Currently feature `asm` can only be enabled on x86_64 arch.
warning: build failed, waiting for other jobs to finish...
``` 

**My machine:** 
MacBook Pro
Apple M1 Pro
OS: 14.2.1 (23C71)

**Comment by avras** [comment]
`cargo build --release` works fine on Ubuntu 22.04.1 for me. Have you tried building [Nova](https://github.com/microsoft/Nova) on your machine? It seems to have a `halo2curves\asm` feature. See [this line](https://github.com/microsoft/Nova/blob/9d0edf291e04c5e9501c665ecc6c6f5623222cf0/Cargo.toml#L78).

**Comment by tumberger** [comment]
Adding
`nova-snark = { version = "0.36.0", default-features = false }`
to your cargo.toml should solve this issue
